#################################################
# Makefile
#################################################


job-debian8-makefile-gcc:

  tags: [ "docker-debian8" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:8
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux-desktop


job-debian8-makefile-clang:

  tags: [ "docker-debian8" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:8
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .scheduled-job-linux-desktop


#################################################
# Ninja
#################################################


job-debian8-ninja-gcc:

  tags: [ "docker-debian8" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:8
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .job-linux-desktop


job-debian8-ninja-gcc-novideo:

  only:
    - schedules
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
  extends: job-debian8-ninja-gcc


job-debian8-ninja-clang:

  tags: [ "docker-debian8" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:8
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .job-linux-desktop


job-debian8-ninja-clang-novideo:

  only:
    - schedules
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
  extends: job-debian8-ninja-clang


#test-bctoolbox-debian8:
#  extends: .test-bctoolbox
#  dependencies:
#    - job-debian8-ninja-clang
#  tags: [ "docker-test-debian8" ]

test-bellesip-debian8:
  extends: .test-bellesip
  dependencies:
    - job-debian8-ninja-clang
  tags: [ "docker-test-debian8" ]
  
test-belr-debian8:
  extends: .test-belr
  dependencies:
    - job-debian8-ninja-clang
  tags: [ "docker-test-debian8" ]
  
test-belcard-debian8:
  extends: .test-belcard
  dependencies:
    - job-debian8-ninja-clang
  tags: [ "docker-test-debian8" ]
  
test-bzrtp-debian8:
  extends: .test-bzrtp
  dependencies:
    - job-debian8-ninja-clang
  tags: [ "docker-test-debian8" ]