#################################################
# Makefile
#################################################


job-debian8-makefile-gcc:

  tags: [ "docker-debian8" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:8
  only:
    variables:
      - $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .job-linux-desktop  
  
#################################################
# TESTS
#################################################

#Commented until fix for broken ipv6
#test-bctoolbox-debian8:
#  extends: .test-bctoolbox
#  dependencies:
#    - job-debian8-ninja-clang
#  tags: [ "docker-test-debian8" ]

test-bellesip-debian8:
  extends: .test-bellesip
  dependencies:
    - job-debian8-makefile-gcc
  tags: [ "docker-test-debian8-nuc" ]
  
test-belr-debian8:
  extends: .test-belr
  dependencies:
    - job-debian8-makefile-gcc
  tags: [ "docker-test-debian8-nuc" ]
  
test-belcard-debian8:
  extends: .test-belcard
  dependencies:
    - job-debian8-makefile-gcc
  tags: [ "docker-test-debian8-nuc" ]
  
test-bzrtp-debian8:
  extends: .test-bzrtp
  dependencies:
    - job-debian8-makefile-gcc
  tags: [ "docker-test-debian8-nuc" ]
  
test-liblinphone-debian8:
  tags: [ "docker-test-debian8-liblinphone-nuc" ]
  extends: .test-liblinphone
  dependencies:
    - job-debian8-makefile-gcc
