#################################################
# Makefile
#################################################


# job-raspbian-makefile-gcc:
#   allow_failure: true
#   tags: [ "docker" ]
#   image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-raspbian
#   extends: .linux-prepare
#   rules:
  # rules:
  #   - if: $CI_PIPELINE_SOURCE == "schedule" && $ALL_LINUX_BUILDS != null && $SKIP_LINUX == null
  #   - !reference [.rules-merge-request-manual, rules]
#   variables:
#     CMAKE_GENERATOR: Unix Makefiles
#   stage: build

#   script:
#     - mkdir -p build-raspberry
#     - cd build-raspberry
#     - cmake .. -G "$CMAKE_GENERATOR" -DLINPHONESDK_PLATFORM=Raspberry $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS
#     - echo $CMAKE_GENERATOR
#     - echo $DEFAULT_LINUX_CMAKE_OPTIONS
#     - echo $CMAKE_OPTIONS
#     - cmake --build . --target sdk -- $ADDITIONAL_BUILD_OPTIONS
#     - echo $ADDITIONAL_BUILD_OPTIONS
#   artifacts:
#     paths:
#       - build-raspberry/linphone-sdk/raspberry/bin/*
#       - build-raspberry/linphone-sdk/raspberry/lib/*
#       - build-raspberry/linphone-sdk/raspberry/lib64/*
#       - build-raspberry/linphone-sdk/raspberry/include/*
#       - build-raspberry/linphone-sdk/raspberry/share/*
#       - build-raspberry/WORK/raspberry/Build/bctoolbox/tester/*
#       - build-raspberry/WORK/raspberry/Build/bzrtp/test/*
#       #Lime data folder isn't installed at  the right place !
#       #We have to find it and add it manually...
#       - lime/tester/*
#       - linphone/tester/*
#     expire_in: 1 week
