#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_centos8: &docker_image_platform_and_runner_tag
  tags: [ "docker-test" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    PLATFORM: linux-centos8

#################################################
# Makefile
#################################################


centos8-makefile-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
    CC: gcc
    CXX: g++
  extends: .linux-desktop


centos8-makefile-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
    CC: clang
    CXX: clang++
  extends: .linux-desktop


#################################################
# Ninja
#################################################


centos8-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .linux-desktop


centos8-ninja-gcc-novideo:

  tags: [ "docker" ]
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
  extends: centos8-ninja-gcc


centos8-ninja-clang:

  tags: [ "docker" ]
  rules:
    - if: $NIGHTLY_MASTER
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
  extends: .linux-desktop


centos8-ninja-clang-novideo:

  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
  extends: centos8-ninja-clang


#################################################
# TESTS
#################################################


bctoolbox-centos8-test:
  extends: .test-bctoolbox
  needs:
    - centos8-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bellesip-centos8-test:
  extends: .test-bellesip
  needs:
    - centos8-ninja-gcc
  #different runner needed because belle-sip_tester can't work in parallel (dialog test suite is crashing randomly)
  tags: [ "docker-sequential" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8:$CENTOS_8_IMAGE_VERSION
  variables:
    PLATFORM: linux-centos8

belr-centos8-test:
  extends: .test-belr
  needs:
    - centos8-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

belcard-centos8-test:
  extends: .test-belcard
  needs:
    - centos8-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bzrtp-centos8-test:
  extends: .test-bzrtp
  needs:
    - centos8-ninja-gcc
  <<: *docker_image_platform_and_runner_tag
#mediastreamer-centos8-test:
#  tags: [ "docker-test-centos8-liblinphone-nuc" ]
#  extends: .test
#  needs:
#    - centos8-ninja-gcc
#  variables:
#    TESTER_BIN: "mediastreamer2_tester"
#    PULSEAUDIO: "pulseaudio -D -L module-virtual-source --exit-idle-time=-1"
#    PULSEAUDIO_KILL: "pulseaudio --kill"
#    LOG_PATTERN: "logMediastreamerAllPar"
#    PATH_TO_TESTER: "${CI_PROJECT_DIR}/build-desktop/linphone-sdk/desktop/bin"
#    SET_CAP_SYS_NICE_NET_ADMIN_MS: "sudo setcap cap_net_admin,cap_sys_nice+ep ./${TESTER_BIN}"
#    PLATFORM: linux-centos8

liblinphone-centos8-test:
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos8-test-liblinphone:$CENTOS_8_TEST_LIBLIN_IMAGE_VERSION
  extends: .test-liblinphone
  needs:
    - centos8-ninja-gcc
  variables:
    PLATFORM: linux-centos8
