#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_centos7: &docker_image_needs_platform_runner_tag_dev_toolset
  tags: [ "docker-test" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7:$CENTOS_7_IMAGE_VERSION
  needs:
    - centos7-ninja-gcc
  variables:
    PLATFORM: linux-centos7
  before_script:
    - source /opt/rh/devtoolset-8/enable




#################################################
# Makefile
#################################################


centos7-makefile-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7:$CENTOS_7_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
    CC: gcc
    CXX: g++
  extends: .linux-desktop


#################################################
# Ninja
#################################################


centos7-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7:$CENTOS_7_IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .linux-desktop
#################################################
# TESTS
#################################################

bctoolbox-centos7-test:
  extends: .test-bctoolbox
  <<: *docker_image_needs_platform_runner_tag_dev_toolset

belr-centos7-test:
  extends: .test-belr
  <<: *docker_image_needs_platform_runner_tag_dev_toolset

# belr-centos7-test-mr:
#   extends: .test-belr-mr
#   <<: *docker_image_needs_platform_runner_tag_dev_toolset

belcard-centos7-test:
  extends: .test-belcard
  <<: *docker_image_needs_platform_runner_tag_dev_toolset

# belcard-centos7-test-mr:
#   extends: .test-belcard-mr
#   <<: *docker_image_needs_platform_runner_tag_dev_toolset

bzrtp-centos7-test:
  extends: .test-bzrtp
  <<: *docker_image_needs_platform_runner_tag_dev_toolset

# bzrtp-centos7-test-mr:
#   extends: .test-bzrtp-mr
#   <<: *docker_image_needs_platform_runner_tag_dev_toolset

.factorize_bs_centos7: &docker_image_needs_tag_platform_devtoolset_bs
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7:$CENTOS_7_IMAGE_VERSION
  needs:
    - centos7-ninja-gcc
  #different runner needed because belle-sip_tester can't work in parallel (dialog test suite is crashing randomly)
  tags: [ "docker-sequential" ]
  variables:
    PLATFORM: linux-centos7
  before_script:
    - source /opt/rh/devtoolset-8/enable

bellesip-centos7-test:
  extends: .test-bellesip
  <<: *docker_image_needs_tag_platform_devtoolset_bs

# bellesip-centos7-test-mr:
#   extends: .test-bellesip-mr
#   <<: *docker_image_needs_tag_platform_devtoolset_bs

.factorize_ms2_centos7: &docker_image_needs_platform_devtoolset_ms
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7-test-liblinphone:$CENTOS_7_TEST_LIBLIN_IMAGE_VERSION
  needs:
    - centos7-ninja-gcc
  variables:
    PLATFORM: linux-centos7
  before_script:
    - source /opt/rh/devtoolset-8/enable

mediastreamer-centos7-test:
  extends: .test-mediastreamer
  <<: *docker_image_needs_platform_devtoolset_ms

# mediastreamer-centos7-test-mr:
#   extends: .test-mediastreamer-mr
#   <<: *docker_image_needs_platform_devtoolset_ms

.factorize_liblinphone_centos7: &docker_image_needs_platform_devtoolset_libl
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-centos7-test-liblinphone:$CENTOS_7_TEST_LIBLIN_IMAGE_VERSION
  needs:
    - centos7-ninja-gcc
  variables:
    PLATFORM: linux-centos7
  before_script:
    - source /opt/rh/devtoolset-8/enable

liblinphone-centos7-test:
  extends: .test-liblinphone
  <<: *docker_image_needs_platform_devtoolset_libl

liblinphone-centos7-test-mr:
  extends: .test-liblinphone-mr
  <<: *docker_image_needs_platform_devtoolset_libl

liblinphone-centos7-test-force:
  extends: .test-liblinphone
  <<: *docker_image_needs_platform_devtoolset_libl
  rules:
    - if: $ENABLE_TESTS_LIBLINPHONE
