#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_debian9: &docker_image_platform_and_runner_tag
  tags: [ "docker-test" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian9

#################################################
# Makefile
#################################################


#debian9-makefile-gcc:
#
#  tags: [ "docker" ]
#  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
# rules:
#   - if: $NIGHTLY_MASTER
#  variables:
#    CMAKE_GENERATOR: Unix Makefiles
#    CC: gcc
#    CXX: g++
#    #Only used to overwrite value set by .set_parallel_level.yml
#    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
#  extends: .linux-desktop


debian9-makefile-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
  extends: .linux-desktop


#################################################
# Ninja
#################################################


debian9-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_LINUX == null
  variables:
    CMAKE_OPTIONS: -DENABLE_DOC=ON -DENABLE_LDAP=ON
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
  extends: .linux-desktop


#debian9-ninja-gcc-novideo:
#
#  rules:
#   - if: $NIGHTLY_MASTER
#  variables:
#    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=ON
#  extends: debian9-ninja-gcc


debian9-ninja-gcc-smallsdk:

  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_ADVANCED_IM=NO -DENABLE_DB_STORAGE=NO -DENABLE_FLEXIAPI=NO -DENABLE_LDAP=NO
  extends: debian9-ninja-gcc


#job-debian9-ninja-clang:

#  tags: [ "docker" ]
#  rules:
#   - if: $NIGHTLY_MASTER
#  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
#  variables:
#    CMAKE_OPTIONS: -DENABLE_DOC=ON
#    CMAKE_GENERATOR: Ninja
#    CC: clang
#    CXX: clang++
#  extends: .linux-desktop


#job-debian9-ninja-clang-novideo:
#  rules:
#   - if: $NIGHTLY_MASTER
#  variables:
#    CMAKE_OPTIONS: -DENABLE_VIDEO=NO
#  extends: job-debian9-ninja-clang

#################################################
# TESTS
#################################################


#Commented until fix for ipv6 for debian 8/9
bctoolbox-debian9-test:
  extends: .test-bctoolbox
  needs:
    - debian9-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bellesip-debian9-test:
  extends: .test-bellesip
  needs:
    - debian9-ninja-gcc
  tags: [ "docker-sequential" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9:$DEBIAN_9_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian9

belr-debian9-test:
  extends: .test-belr
  needs:
    - debian9-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

belcard-debian9-test:
  extends: .test-belcard
  needs:
    - debian9-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

bzrtp-debian9-test:
  extends: .test-bzrtp
  needs:
    - debian9-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

liblinphone-debian9-test:
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian9-test-liblinphone:$DEBIAN_9_TEST_LIBLIN_IMAGE_VERSION
  extends: .test-liblinphone
  needs:
    - debian9-ninja-gcc
  variables:
    PLATFORM: linux-debian9
