#Build template to use in other job scripts without having to copy same code
#format = .className: &referenceName
#Use = "<< *referenceName" to use the template ("-*" in script)


.factorize_debian11: &docker_image_platform_and_runner_tag
  tags: [ "docker-test" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian11

#################################################
# Makefile
#################################################


debian11-makefile-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: gcc
    CXX: g++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


debian11-makefile-clang:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    CC: clang
    CXX: clang++
    ADDITIONAL_BUILD_OPTIONS: -j$MAKEFILE_JOBS
  extends: .linux-desktop


#################################################
# Ninja
#################################################


debian11-ninja-gcc:

  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: gcc
    CXX: g++
    CMAKE_OPTIONS: -DENABLE_LDAP=NO
  extends: .linux-desktop


debian11-ninja-gcc-novideo:
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=NO
  extends: debian11-ninja-gcc


debian11-ninja-gcc-smallsdk:
  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_ADVANCED_IM=NO -DENABLE_DB_STORAGE=NO -DENABLE_FLEXIAPI=NO -DENABLE_LDAP=NO
  extends: debian11-ninja-gcc


debian11-ninja-clang:

  rules:
    - if: $NIGHTLY_MASTER
  tags: [ "docker" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  variables:
    CMAKE_GENERATOR: Ninja
    CC: clang
    CXX: clang++
    CMAKE_OPTIONS: -DENABLE_LDAP=NO
  extends: .linux-desktop

debian11-ninja-clang-sanitizer:
  variables:
    CMAKE_SANITIZER_OPTIONS: -DENABLE_SANITIZER=YES
  extends: debian11-ninja-clang


debian11-ninja-clang-novideo:
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=NO
  extends: debian11-ninja-clang

#################################################
# TESTS
#################################################



test-bctoolbox-debian11:
  extends: .test-bctoolbox
  needs:
    - debian11-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

test-bellesip-debian11:
  extends: .test-bellesip
  needs:
    - debian11-ninja-gcc
  #different runner needed because belle-sip_tester can't work in parallel (dialog test suite is crashing randomly)
  tags: [ "docker-sequential" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11:$DEBIAN_11_IMAGE_VERSION
  variables:
    PLATFORM: linux-debian11

test-belr-debian11:
  extends: .test-belr
  needs:
    - debian11-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

test-belcard-debian11:
  extends: .test-belcard
  needs:
    - debian11-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

test-bzrtp-debian11:
  extends: .test-bzrtp
  needs:
    - debian11-ninja-gcc
  <<: *docker_image_platform_and_runner_tag

test-liblinphone-debian11:
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11-test-liblinphone:$DEBIAN_11_TEST_LIBLIN_IMAGE_VERSION
  extends: .test-liblinphone
  needs:
    - debian11-ninja-gcc
  variables:
    PLATFORM: linux-debian11

# test-liblinphone-debian11-mr:
#   extends: .test-liblinphone-mr
#   image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian11-test-liblinphone:$DEBIAN_11_TEST_LIBLIN_IMAGE_VERSION
#   needs:
#     - debian11-ninja-gcc
#   variables:
#     PLATFORM: linux-debian11
