.macosx-desktop:

  extends: .job-prepare
  stage: build
  tags: [ "macosx-xcode11" ]

  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") && $DOCKER_UPDATE == null && $SKIP_MACOSX == null
    - if: $CI_PIPELINE_SOURCE == "schedule" && $DOCKER_UPDATE == null && $SKIP_MACOSX == null

  variables:
    CMAKE_OPTIONS: -DENABLE_LDAP=ON
    LINPHONESDK_MACOS_ARCHS: "x86_64"
    LINPHONESDK_OPENSSL_ROOT_DIR_X86_64: "/usr/local/opt/openssl@1.1"
    LINPHONESDK_OPENSSL_ROOT_DIR_ARM64: "/opt/homebrew/opt/openssl@1.1"

  script:
    - !reference [.set-max-jobs-unix, script]
    - echo $MACOS_DEPLOY_URL
    - echo $XCODE_OPTIONS
    - ccache -s
    - if [ -d "build-desktop" ]; then rm -rf build-desktop; fi;
    - mkdir -p build-desktop
    - cd build-desktop
    - echo $CMAKE_GENERATOR
    - echo $DEFAULT_CMAKE_OPTIONS
    - echo $CMAKE_OPTIONS
    - echo $LINPHONESDK_MACOS_ARCHS
    - echo $LINPHONESDK_OPENSSL_ROOT_DIR_X86_64
    - echo $LINPHONESDK_OPENSSL_ROOT_DIR_ARM64
    - cmake .. -G "$CMAKE_GENERATOR" -DLINPHONESDK_PLATFORM=Desktop -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DLINPHONESDK_MACOS_ARCHS="$LINPHONESDK_MACOS_ARCHS" -DLINPHONESDK_OPENSSL_ROOT_DIR_X86_64="$LINPHONESDK_OPENSSL_ROOT_DIR_X86_64" -DLINPHONESDK_OPENSSL_ROOT_DIR_ARM64="$LINPHONESDK_OPENSSL_ROOT_DIR_ARM64" $DEFAULT_CMAKE_OPTIONS $XCODE_OPTIONS $CMAKE_OPTIONS $SCHEDULE_CMAKE_OPTIONS
    - cmake --build . --target sdk -- $ADDITIONAL_BUILD_OPTIONS
    #used to know the right zip to pick up in tests stage. we parse the git status command to stop at the number of commits
    #and we then use a glob in test stage to get the right archive
    #using only the git describe doesn't work because the commit hashes don't match
    - ls -t linphone-sdk-*.zip > sdk_archive_name.txt
    - cat sdk_archive_name.txt
    - ccache -s
    - echo $(git describe) > gitdescribe.txt

  artifacts:
    paths:
      - build-desktop/gitdescribe.txt
      - build-desktop/sdk_archive_name.txt
      - build-desktop/linphone-sdk-*.zip
      - build-desktop/linphone-sdk.podspec
      - liblinphone/tester/*
    when: always
    expire_in: 1 week

.macosx-m1-desktop:
  tags: [ "macmini-m1-xcode12" ]
  variables:
    LINPHONESDK_MACOS_ARCHS: "arm64, x86_64"
  extends: .macosx-desktop

#################################################
# Makefile
#################################################


macosx-makefile:

  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
  extends: .macosx-desktop

macosx-m1-makefile:

  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_GENERATOR: Unix Makefiles
    #Only used to overwrite value set by .set_parallel_level.yml
    #ADDITIONAL_BUILD_OPTIONS: -j[jobs]
  extends: .macosx-m1-desktop

#################################################
# Ninja
#################################################


macosx-ninja:

  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DENABLE_UNIT_TESTS=ON -DENABLE_LDAP=ON
  extends: .macosx-desktop

macosx-m1-ninja:

  variables:
    CMAKE_GENERATOR: Ninja
    CMAKE_OPTIONS: -DENABLE_UNIT_TESTS=ON -DENABLE_LDAP=ON
  extends: .macosx-m1-desktop

macosx-ninja-novideo:

  rules:
    - if: $NIGHTLY_MASTER
  variables:
    CMAKE_OPTIONS: -DENABLE_VIDEO=NO -DENABLE_LDAP=ON
  extends: macosx-ninja


#################################################
# XCode
#################################################


macosx-xcode:
  extends: .macosx-m1-desktop
  variables:
    CMAKE_GENERATOR: Xcode
    ADDITIONAL_BUILD_OPTIONS: -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=$MAX_NUMBER_TASK

  rules:
    - if: $NIGHTLY_MASTER
    - if: $NIGHTLY_RELEASE
    - if: $DEPLOY_RUN_MACOSX

  # All variables declared in "variables" are processed before "before_script" and "script", so declaring XCODE_OPTIONS (path to base URL) in before_script allows to set it dynamically.
  before_script:
    - MACOS_DEPLOY_URL=$MACOS_RELEASES_URL
    - |
        if [ "$(git -C liblinphone describe) =~ .*(alpha|beta).*" ];
        then MACOS_DEPLOY_URL=$MACOS_SNAPSHOTS_URL
        fi
    - echo $MACOS_DEPLOY_URL
    - XCODE_OPTIONS="-DLINPHONESDK_MACOS_BASE_URL=$MACOS_DEPLOY_URL"
