macosx-upload:
  stage: deploy
  tags: [ "macosx-xcode11" ]

  rules:
    - if: $DEPLOY_RUN_MACOSX
    - if: $NIGHTLY_MASTER
    - if: $NIGHTLY_RELEASE
  variables:
    GIT_FETCH_EXTRA_FLAGS: --tags --force --recurse-submodules=yes
    GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8 --force --recursive
  needs:
    - macosx-xcode

  script:
    - DESCRIBE=$(git -C liblinphone describe)
    - !reference [.choose_upload_dir, script]
    - rsync -rlv --ignore-existing build-desktop/linphone-sdk-*.zip $DEPLOY_SERVER:$UPLOAD_ROOT_DIRECTORY/macosx/sdk
    - pod repo remove linphone-sdk-macosx || true
    - pod repo add linphone-sdk-macosx git@gitlab.linphone.org:BC/public/podspec-macos.git master
    - pod repo push linphone-sdk-macosx build-desktop/linphone-sdk.podspec --skip-import-validation --verbose
    - cd ~/.cocoapods/repos/linphone-sdk-macosx && git push origin master && cd -
    - pod repo remove linphone-sdk-macosx
