job-docker-rebuild-debian10-image:
  stage: docker-update-build
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  script:
    - docker pull debian:buster
    - cd docker-files
    - docker build -f ./bc-dev-debian10 -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10:latestupdated

job-docker-rebuild-debian10-ms-test-image:
  stage: docker-update-build-ms
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  needs:
    - job-docker-rebuild-debian10-image
  script:
    - docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10:latestupdated
    - cd docker-files
    - docker build -f ./bc-dev-debian10-test-mediastreamer -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-mediastreamer:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-mediastreamer:latestupdated

job-docker-rebuild-debian10-liblinphone-test-image:
  stage: docker-update-build-liblinphone
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  needs:
    - job-docker-rebuild-debian10-ms-test-image
  script:
    - docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-mediastreamer:latestupdated
    - cd docker-files
    - docker build -f ./bc-dev-debian10-test-liblinphone -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-liblinphone:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-liblinphone:latestupdated

job-rebuild-debian10-newdocker-makefile-gcc:
  extends: job-debian10-makefile-gcc
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10


job-rebuild-debian10-newdocker-ninja-gcc:
  extends: job-debian10-ninja-gcc
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10

job-rebuild-debian10-newdocker-ninja-gcc-novideo:
  extends: job-debian10-ninja-gcc-novideo
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10

job-rebuild-debian10-newdocker-makefile-clang:
  extends: job-debian10-makefile-clang
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10

job-rebuild-debian10-newdocker-ninja-clang:
  extends: job-debian10-ninja-clang
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10

job-rebuild-debian10-newdocker-ninja-clang-novideo:
  extends: job-debian10-ninja-clang-novideo
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian:10
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10

test-liblinphone-debian10-newdocker:
  extends: test-liblinphone-debian10
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-debian10-test-liblinphone:latestupdated
  rules:
    - if: $DOCKER_UPDATE_DEBIAN10
  needs:
    - job-rebuild-debian10-newdocker-makefile-gcc
