job-docker-rebuild-archlinux-image:
  stage: docker-update-build
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  script:
    - docker pull archlinux/base:latest
    - cd docker-files
    - docker build -f ./bc-dev-archlinux -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated

job-docker-rebuild-archlinux-ms-test-image:
  stage: docker-update-build-ms
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX
  needs:
    - job-docker-rebuild-archlinux-image
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  script:
    - docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
    - cd docker-files
    - docker build -f ./bc-dev-archlinux-test-mediastreamer -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-mediastreamer:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-mediastreamer:latestupdated

job-docker-rebuild-archlinux-liblinphone-test-image:
  stage: docker-update-build-liblinphone
  tags: [ "linux-deploy" ]
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX
  # Prevent tests from fetching repo. They have all needed files in upcoming artifacts
  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: none
  needs:
    - job-docker-rebuild-archlinux-ms-test-image
  script:
    - docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-mediastreamer:latestupdated
    - cd docker-files
    - docker build -f ./bc-dev-archlinux-test-liblinphone -t gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-liblinphone:latestupdated --rm --no-cache .
    - docker login gitlab.linphone.org:4567
    - docker push gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-liblinphone:latestupdated

job-rebuild-archlinux-newdocker-makefile-gcc:
  extends: job-archlinux-latest-makefile-gcc
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX


job-rebuild-archlinux-newdocker-ninja-gcc:
  extends: job-archlinux-latest-ninja-gcc
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX

job-rebuild-archlinux-newdocker-ninja-gcc-novideo:
  extends: job-archlinux-latest-ninja-gcc-novideo
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX

job-rebuild-archlinux-newdocker-makefile-clang:
  extends: job-archlinux-latest-makefile-clang
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX

job-rebuild-archlinux-newdocker-ninja-clang:
  extends: job-archlinux-latest-ninja-clang
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX

job-rebuild-archlinux-newdocker-ninja-clang-novideo:
  extends: job-archlinux-latest-ninja-clang-novideo
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX

test-liblinphone-archlinux-newdocker:
  extends: test-liblinphone-arch
  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-archlinux-test-liblinphone:latestupdated
  rules:
    - if: $DOCKER_UPDATE_ARCHLINUX
  needs:
    - job-rebuild-archlinux-newdocker-makefile-gcc
